name: 🐛 Bug Report
description: Report a bug or unexpected behavior with the integration
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug! 🙏
        Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened instead...
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2024.1.0"
    validations:
      required: true

  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: What version of Uber Eats Order Tracker are you using?
      placeholder: "1.2.0"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install the integration?
      options:
        - HACS
        - Manual
    validations:
      required: true

  - type: dropdown
    id: issue-area
    attributes:
      label: Problem Area
      description: Where is the issue occurring?
      options:
        - Sidebar Panel
        - Sensors/Entities
        - Device Tracker
        - Configuration/Setup
        - Authentication/Cookies
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please provide any relevant logs from Home Assistant.
        Go to Settings → System → Logs and filter by "uber_eats"
      render: shell
      placeholder: Paste logs here...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of the integration
          required: true
        - label: I have restarted Home Assistant after updating
          required: true
